# Numpy_Assignment_2::

## Question:1

### Convert a 1D array to a 2D array with 2 rows?

#### Desired output::

array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [7]:
import numpy as np
x = np.arange(10).reshape(2,5)
x

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

## Question:2

###  How to stack two arrays vertically?

#### Desired Output::

In [12]:
x = np.arange(10).reshape(2,5)
y = np.ones((2,5), dtype=int)
np.vstack([x,y])

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

## Question:3

### How to stack two arrays horizontally?

#### Desired Output::

In [13]:
np.hstack([x,y])

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

## Question:4

### How to convert an array of arrays into a flat 1d array?

#### Desired Output::

In [14]:
x = np.arange(10).reshape(2,5)
print (x)
x.flatten()

[[0 1 2 3 4]
 [5 6 7 8 9]]


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Question:5

### How to Convert higher dimension into one dimension?

#### Desired Output::

In [17]:
x = np.arange(15).reshape(1,3,5)
print (x)
x.flatten()

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]]


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

## Question:6

### Convert one dimension to higher dimension?

#### Desired Output::

In [18]:
x = np.arange(15).reshape(5,3)
x

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

## Question:7

### Create 5x5 an array and find the square of an array?

In [19]:
x = np.arange(25).reshape(5,5)
x**2

array([[  0,   1,   4,   9,  16],
       [ 25,  36,  49,  64,  81],
       [100, 121, 144, 169, 196],
       [225, 256, 289, 324, 361],
       [400, 441, 484, 529, 576]], dtype=int32)

## Question:8

### Create 5x6 an array and find the mean?

In [20]:
x = np.arange(30).reshape(5,6)
x.mean()

14.5

## Question:9

### Find the standard deviation of the previous array in Q8?

In [21]:
np.std(x)

8.65544144839919

## Question:10

### Find the median of the previous array in Q8?

In [22]:
np.median(x)

14.5

## Question:11

### Find the transpose of the previous array in Q8?

In [23]:
x.transpose()

array([[ 0,  6, 12, 18, 24],
       [ 1,  7, 13, 19, 25],
       [ 2,  8, 14, 20, 26],
       [ 3,  9, 15, 21, 27],
       [ 4, 10, 16, 22, 28],
       [ 5, 11, 17, 23, 29]])

## Question:12

### Create a 4x4 an array and find the sum of diagonal elements?

In [26]:
x = np.arange(16).reshape(4,4)
np.trace(x)

30

## Question:13

### Find the determinant of the previous array in Q12?

In [28]:
np.linalg.det(x)

-2.9582283945787796e-30

## Question:14

### Find the 5th and 95th percentile of an array?

In [31]:
print ("5th Percentile - ", np.percentile(x,5))
print ("95th Percentile - ", np.percentile(x,95))

5th Percentile -  0.75
95th Percentile -  14.25


## Question:15

### How to find if a given array has any null values?

In [32]:
x = np.array([1,2,3,np.nan])
print ("Our Array", x)
print ("Checking null values with np.isnan(x)", np.isnan(x))

Our Array [ 1.  2.  3. nan]
Checking null values with np.isnan(x) [False False False  True]
